### ISSUE TITLE
Is this repo unmaintained?

### ISSUE THREAD

**Issue by nfirvine** [sgerrand/xfce4-terminal-colors-solarized#11]
Bug #9 has been open for years. The format of the variable changed years ago. http://askubuntu.com/questions/315230/solarized-theme-in-terminal-vim-on-xubuntu

It's completely broken.

If it is unmaintained, please put up a notice and inform upstream (which frankly looks unmaintained as well).

**Comment by sgerrand** [comment]
Thanks for raising this issue. I'll follow it up this week. I haven't been
using Xfce as my day to day desktop for a while, hence the delays.

:thought_balloon: Perhaps seeking a new active maintainer is the way
forward.

**Comment by nfirvine** [comment]
It may be obsolete? Looks like xfce-terminal has had solarized baked into it for some time: http://git.xfce.org/apps/xfce4-terminal/commit/colorschemes/solarized-light.theme.in?id=0aab08157c72b4b76587cf89f8d4f1f235f2da24

**Comment by sgerrand** [comment]
@nfirvine: Xfce added the Solarized configuration about 2 years after the fact, but it is not available in all distributions. For that reason, I've kept this repository up.

Your point regarding adding a notice is valid and I'll add an issue to specifically address that.

**Comment by nfirvine** [comment]
Thanks @sgerrand. Sorry to be a pain in the ass, just see a lot of repos where the canonical one has critical bugs but is unmaintained..

**Comment by sgerrand** [comment]
> Thanks @sgerrand. Sorry to be a pain in the ass, just see a lot of repos
where the canonical one has critical bugs but is unmaintained..

No worries, the question was a reasonable one.
