### ISSUE TITLE
Wrong colours in xfce4-terminal 0.6.1 on Ubuntu 13.04

### ISSUE THREAD

**Issue by svenXY** [sgerrand/xfce4-terminal-colors-solarized#9]
Hi,

after copying the terminalrc to ~/.config/xfce4/terminal/terminalrc the background colour is somewhat OK, but ls -l is still not solarized and mutt sucks like hell (though using the mutt solarized colour palette, which works fine in e.g. terminator or guake on the same PC.

I'm using c5326d1b47c5cccb05384d742cb58c42ac3d4709 which should be up to date

Here's a screenshot of a directory listing:
![solarized_not](https://f.cloud.github.com/assets/635904/1940834/3b1ff214-7f80-11e3-813f-11ecd5ec1243.png)

Thanks for checking,
Sven

**Comment by nfirvine** [comment]
Progress?

**Comment by sgerrand** [comment]
Fixed in #10.
